package com.example.rules

import java.util.*

import com.example.*


rule "Rule that breaks ExecutableModel"
@filename("rules.drl")
ruleflow-group "RFG-1"
salience 5
no-loop true
    when
        $list: List()
        $cwvs:    (
            List(size > 0) from collect ( ClassWithValue(value == null) ) or
            List(size > 0) from collect ( ClassWithValue(value != null) )
        )
    then
        $list.addAll($cwvs);
end
